### ISSUE TITLE
how about right leg?

### ISSUE THREAD

**Issue by xlla** [SkyentificGit/SmallRobotArm#7]
I am plan to diy this wonderful arm, but I am not found stl for right leg.

**Comment by langster1980** [comment]
Hi, in your 3d printer slicer program mirror the left leg! It becomes the
right leg!

Hope this helps...I have nearly printed it all. I need to get some laser
cutting done instead of carbon fibre and buy another motor...

Good luck

Alex

**Comment by xlla** [comment]
ok, I learned it, thank you very much.
